#!/usr/bin/env bash
set -euo pipefail

# Stage1-only defaults and launcher.  The existing train_base.sh remains the
# single Stage1 execution implementation; this file owns its public defaults.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"
LABRAM_BASE_ROOT="${LABRAM_BASE_ROOT:-${PROJECT_ROOT}}"
LABRAM_BASE_ROOT="$(cd "${LABRAM_BASE_ROOT}" && pwd)"
exporexport PYTHONPATH="${PROJECT_ROOT}${PYTHONPATH:+:${PYTHONPATH}}"t LABRAM_BASE_ROOT


EXP_NAME="${EXP_NAME:-stage1_default}"
RUN_PREFIX="${RUN_PREFIX:-${EXP_NAME}}"
SEED="${SEED:-0}"
SCOPE="${SCOPE:-missing}"
MISSING_FILL="${MISSING_FILL:-prototype}"
OUTPUT_BASE="${OUTPUT_BASE:-prototype}"
COMPONENT_MODE="${COMPONENT_MODE:-identity}"
COMPOSITION_MODE="${COMPOSITION_MODE:-sum}"
SUB_CONTRA_WEIGHT="${SUB_CONTRA_WEIGHT:-1}"
TASK_CONTRA_WEIGHT="${TASK_CONTRA_WEIGHT:-1}"
SWAP_SUB_WEIGHT="${SWAP_SUB_WEIGHT:-1}"
SWAP_TASK_WEIGHT="${SWAP_TASK_WEIGHT:-1}"
RECON_WEIGHT="${RECON_WEIGHT:-0}"
MISSING_MSE_WEIGHT="${MISSING_MSE_WEIGHT:-0}"
TEMPERATURE="${TEMPERATURE:-0.2}"
EPOCHS="${EPOCHS:-50}"
BATCH_SIZE="${BATCH_SIZE:-64}"
LR="${LR:-5e-4}"
MIN_LR="${MIN_LR:-1e-6}"
WEIGHT_DECAY="${WEIGHT_DECAY:-0.05}"
OPTIMIZER="${OPTIMIZER:-adamw}"
SCHEDULE="${SCHEDULE:-cosine}"
WARMUP_EPOCHS="${WARMUP_EPOCHS:-5}"
OPT_EPS="${OPT_EPS:-1e-8}"
UNFREEZE_CNN="${UNFREEZE_CNN:-0}"
CNN_LR_MULT="${CNN_LR_MULT:-0.1}"
SAMPLING="${SAMPLING:-cslpae}"
DATA_PATH="${DATA_PATH:-/inspire/ssd/tenant_predefaa-9a1b-4522-bb10-8850f313be13/global_user/7461-chenxinhe/eeg-main/CSLP-AE/data_preparation/simple_data.pt}"
CNN_CHECKPOINT="${CNN_CHECKPOINT:-${LABRAM_BASE_ROOT}/checkpoints/labram-base.pth}"
PROTOTYPE_CHECKPOINT="${PROTOTYPE_CHECKPOINT:-${LABRAM_BASE_ROOT}/docs/prototypes/01_erpcore28_cnn_patch_embed_mean.pth}"
SAMPLING_RATE="${SAMPLING_RATE:-200}"
NORM_METHOD="${NORM_METHOD:-z_score}"
INPUT_SCALE="${INPUT_SCALE:-1.0}"
NUM_WORKERS="${NUM_WORKERS:-4}"
PIN_MEM="${PIN_MEM:-1}"
DEVICE="${DEVICE:-cuda}"
GPU_IDS="${GPU_IDS:-0}"
BACKGROUND="${BACKGROUND:-1}"
DRY_RUN="${DRY_RUN:-0}"
OUTPUT_ROOT="${OUTPUT_ROOT:-${PROJECT_ROOT}/outputs/${RUN_PREFIX}}"

make_abs() {
    if [[ "$1" == /* ]]; then printf '%s\n' "$1"; else printf '%s/%s\n' "${PROJECT_ROOT}" "$1"; fi
}
DATA_PATH="$(make_abs "${DATA_PATH}")"
CNN_CHECKPOINT="$(make_abs "${CNN_CHECKPOINT}")"
PROTOTYPE_CHECKPOINT="$(make_abs "${PROTOTYPE_CHECKPOINT}")"
OUTPUT_ROOT="$(make_abs "${OUTPUT_ROOT}")"

export EXP_NAME RUN_PREFIX SEED SCOPE MISSING_FILL OUTPUT_BASE COMPONENT_MODE COMPOSITION_MODE
export SUB_CONTRA_WEIGHT TASK_CONTRA_WEIGHT SWAP_SUB_WEIGHT SWAP_TASK_WEIGHT
export RECON_WEIGHT MISSING_MSE_WEIGHT TEMPERATURE EPOCHS BATCH_SIZE LR MIN_LR
export WEIGHT_DECAY OPTIMIZER SCHEDULE WARMUP_EPOCHS OPT_EPS UNFREEZE_CNN CNN_LR_MULT
export SAMPLING DATA_PATH CNN_CHECKPOINT PROTOTYPE_CHECKPOINT SAMPLING_RATE NORM_METHOD
export INPUT_SCALE NUM_WORKERS PIN_MEM DEVICE GPU_IDS BACKGROUND DRY_RUN OUTPUT_ROOT

if [[ "${MISSING_FILL}" == "none" ]]; then
    echo "Stage1 MISSING_FILL=none is invalid; use not_applicable for FULL." >&2
    exit 2
fi

exec "${SCRIPT_DIR}/train_base.sh" "$@"
